wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.2
ent_coef:
  value: 0
gamma:
  value: 0.829426073682249
learning_rate:
  value: 0.0003
log_std_init:
  value: 0
n_steps:
  value: 512
total_timesteps:
  value: 20000
