wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.2
ent_coef:
  value: 0.001
gamma:
  value: 0.9075281487655512
learning_rate:
  value: 0.0001
log_std_init:
  value: -2
n_steps:
  value: 1024
total_timesteps:
  value: 20000
