wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.3
ent_coef:
  value: 0.001
gamma:
  value: 0.8888349665544346
learning_rate:
  value: 0.0003
log_std_init:
  value: -2
n_steps:
  value: 1024
total_timesteps:
  value: 20000
