wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.2
ent_coef:
  value: 0.001
gamma:
  value: 0.8627525242915308
learning_rate:
  value: 3.0e-05
log_std_init:
  value: -1
n_steps:
  value: 512
total_timesteps:
  value: 20000
