wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.2
ent_coef:
  value: 0.001
gamma:
  value: 0.8136638715752066
learning_rate:
  value: 0.0001
log_std_init:
  value: 2
n_steps:
  value: 512
total_timesteps:
  value: 20000
