wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.2
ent_coef:
  value: 0.001
gamma:
  value: 0.9114710274306408
learning_rate:
  value: 0.0001
log_std_init:
  value: 1
n_steps:
  value: 1024
total_timesteps:
  value: 20000
