wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.1
ent_coef:
  value: 0.01
gamma:
  value: 0.982959385093852
learning_rate:
  value: 0.0003
log_std_init:
  value: 2
n_steps:
  value: 1024
total_timesteps:
  value: 20000
