wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.1
ent_coef:
  value: 0.001
gamma:
  value: 0.8635622183475054
learning_rate:
  value: 3.0e-05
log_std_init:
  value: 2
n_steps:
  value: 1024
total_timesteps:
  value: 20000
