wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.3
ent_coef:
  value: 0.001
gamma:
  value: 0.8584012033487587
learning_rate:
  value: 0.0003
log_std_init:
  value: 0
n_steps:
  value: 512
total_timesteps:
  value: 40000
