wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.1
ent_coef:
  value: 0
gae_lambda:
  value: 1
gamma:
  value: 0.9531278732516624
learning_rate:
  value: 0.0003
log_std_init:
  value: 0
n_steps:
  value: 1024
target_kl:
  value: 0.020430792871401808
