wandb_version: 1

batch_size:
  value: 512
clip_range:
  value: 0.3
ent_coef:
  value: 0
gae_lambda:
  value: 1
gamma:
  value: 0.9268065821538262
learning_rate:
  value: 0.0003
log_std_init:
  value: 2
n_steps:
  value: 256
target_kl:
  value: 0.014666489151676298
