wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.1
ent_coef:
  value: 0.01
gae_lambda:
  value: 0.9
gamma:
  value: 0.8628501422808404
learning_rate:
  value: 0.0003
log_std_init:
  value: 1
n_steps:
  value: 512
target_kl:
  value: 0.004699657380678148
