wandb_version: 1

batch_size:
  value: 512
clip_range:
  value: 0.3
ent_coef:
  value: 0.001
gae_lambda:
  value: 1
gamma:
  value: 0.9550075291205956
learning_rate:
  value: 3.0e-06
log_std_init:
  value: 1
n_steps:
  value: 1024
target_kl:
  value: 0.010169346882522298
