wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.3
ent_coef:
  value: 0.0001
gae_lambda:
  value: 1
gamma:
  value: 0.9213563367505876
learning_rate:
  value: 0.0003
log_std_init:
  value: 2
n_steps:
  value: 256
target_kl:
  value: 0.026271456593879142
