wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.2
ent_coef:
  value: 0.0001
gae_lambda:
  value: 0.9
gamma:
  value: 0.8661282954213548
learning_rate:
  value: 3.0e-06
log_std_init:
  value: -1
n_steps:
  value: 256
target_kl:
  value: 0.017595231394879583
