wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.2
ent_coef:
  value: 0
gae_lambda:
  value: 1
gamma:
  value: 0.8303745372269855
learning_rate:
  value: 3.0e-05
log_std_init:
  value: 2
n_steps:
  value: 256
target_kl:
  value: 0.013653012292992144
