wandb_version: 1

batch_size:
  value: 512
clip_range:
  value: 0.1
ent_coef:
  value: 0.01
gae_lambda:
  value: 0.9
gamma:
  value: 0.8021522484901379
learning_rate:
  value: 3.0e-06
log_std_init:
  value: -2
n_steps:
  value: 1024
target_kl:
  value: 0.005378330068399414
