wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.1
ent_coef:
  value: 0.01
gae_lambda:
  value: 1
gamma:
  value: 0.8929942820312287
learning_rate:
  value: 3.0e-05
log_std_init:
  value: 0
n_steps:
  value: 256
target_kl:
  value: 0.015974735537474537
