wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.2
ent_coef:
  value: 0.01
gae_lambda:
  value: 0.9
gamma:
  value: 0.8683910953395262
learning_rate:
  value: 3.0e-05
log_std_init:
  value: 2
n_steps:
  value: 1024
target_kl:
  value: 0.01635867855002784
