wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.2
ent_coef:
  value: 0.01
gae_lambda:
  value: 0.9
gamma:
  value: 0.9464697645068112
learning_rate:
  value: 3.0e-05
log_std_init:
  value: 0
n_steps:
  value: 256
target_kl:
  value: 0.011205290699052095
