wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.1
ent_coef:
  value: 0
gae_lambda:
  value: 1
gamma:
  value: 0.977145127055302
learning_rate:
  value: 0.0003
log_std_init:
  value: -2
n_steps:
  value: 256
target_kl:
  value: 0.004583565591676593
