wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.2
ent_coef:
  value: 0
gae_lambda:
  value: 0.9
gamma:
  value: 0.8886828939881859
learning_rate:
  value: 3.0e-05
log_std_init:
  value: -1
n_steps:
  value: 512
target_kl:
  value: 0.008807192964759441
