wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.2
ent_coef:
  value: 0.01
gae_lambda:
  value: 1
gamma:
  value: 0.9404711247333456
learning_rate:
  value: 3.0e-06
log_std_init:
  value: 2
n_steps:
  value: 1024
target_kl:
  value: 0.025647745180391212
