wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.1
ent_coef:
  value: 0.01
gae_lambda:
  value: 1
gamma:
  value: 0.814723443340918
learning_rate:
  value: 3.0e-06
log_std_init:
  value: -1
n_steps:
  value: 256
target_kl:
  value: 0.018076838285415574
