wandb_version: 1

batch_size:
  value: 512
clip_range:
  value: 0.2
ent_coef:
  value: 0.0001
gae_lambda:
  value: 0.9
gamma:
  value: 0.9315593028591198
learning_rate:
  value: 3.0e-05
log_std_init:
  value: 0
n_steps:
  value: 256
target_kl:
  value: 0.016236397469123236
