wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.2
ent_coef:
  value: 0.0001
gae_lambda:
  value: 1
gamma:
  value: 0.8348084359957487
learning_rate:
  value: 3.0e-05
log_std_init:
  value: 2
n_steps:
  value: 256
target_kl:
  value: 0.023634093196237573
