wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.2
ent_coef:
  value: 0.0001
gae_lambda:
  value: 1
gamma:
  value: 0.9275466799144207
learning_rate:
  value: 3.0e-05
log_std_init:
  value: -1
n_steps:
  value: 1024
target_kl:
  value: 0.006020713390445747
