wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.2
ent_coef:
  value: 0.0001
gae_lambda:
  value: 1
gamma:
  value: 0.9961158223047908
learning_rate:
  value: 0.0003
log_std_init:
  value: -1
n_steps:
  value: 256
target_kl:
  value: 0.008509201750953582
