wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.2
ent_coef:
  value: 0.0001
gae_lambda:
  value: 1
gamma:
  value: 0.9346709661300864
learning_rate:
  value: 0.0003
log_std_init:
  value: 1
n_steps:
  value: 512
target_kl:
  value: 0.011609461987351976
