wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.3
ent_coef:
  value: 0.001
gae_lambda:
  value: 0.9
gamma:
  value: 0.8583706398664401
learning_rate:
  value: 0.0003
log_std_init:
  value: 1
n_steps:
  value: 512
target_kl:
  value: 0.02891286209140864
