wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.1
ent_coef:
  value: 0.0001
gae_lambda:
  value: 1
gamma:
  value: 0.8989829444415897
learning_rate:
  value: 3.0e-05
log_std_init:
  value: -2
n_steps:
  value: 1024
target_kl:
  value: 0.013744443954778186
