wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.3
ent_coef:
  value: 0.01
gae_lambda:
  value: 1
gamma:
  value: 0.9498084515934716
learning_rate:
  value: 3.0e-06
log_std_init:
  value: 2
n_steps:
  value: 512
target_kl:
  value: 0.017237355320728263
