wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.1
ent_coef:
  value: 0.001
gae_lambda:
  value: 1
gamma:
  value: 0.8222425217165847
learning_rate:
  value: 0.0003
log_std_init:
  value: 0
n_steps:
  value: 512
target_kl:
  value: 0.02735781247950948
