wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.2
ent_coef:
  value: 0.0001
gae_lambda:
  value: 1
gamma:
  value: 0.8637614496593572
learning_rate:
  value: 3.0e-05
log_std_init:
  value: -2
n_steps:
  value: 512
target_kl:
  value: 0.015257476494078586
