wandb_version: 1

batch_size:
  value: 512
clip_range:
  value: 0.1
ent_coef:
  value: 0.0001
gae_lambda:
  value: 1
gamma:
  value: 0.9011455190088126
learning_rate:
  value: 0.0003
log_std_init:
  value: 0
n_steps:
  value: 512
target_kl:
  value: 0.015992415539910206
