wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.2
ent_coef:
  value: 0.0001
gae_lambda:
  value: 1
gamma:
  value: 0.8829559300972641
learning_rate:
  value: 3.0e-06
log_std_init:
  value: -1
n_steps:
  value: 512
target_kl:
  value: 0.02763018044564251
