wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.3
ent_coef:
  value: 0.001
gae_lambda:
  value: 0.9
gamma:
  value: 0.8988357227051933
learning_rate:
  value: 3.0e-06
log_std_init:
  value: 0
n_steps:
  value: 1024
target_kl:
  value: 0.025971585395714494
