wandb_version: 1

batch_size:
  value: 512
clip_range:
  value: 0.2
ent_coef:
  value: 0.001
gae_lambda:
  value: 0.9
gamma:
  value: 0.8335999103280998
learning_rate:
  value: 0.0003
log_std_init:
  value: -1
n_steps:
  value: 1024
target_kl:
  value: 0.01656335627306777
