wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.3
ent_coef:
  value: 0
gae_lambda:
  value: 1
gamma:
  value: 0.9685851214735556
learning_rate:
  value: 3.0e-05
log_std_init:
  value: -1
n_steps:
  value: 512
target_kl:
  value: 0.027951423322730977
