wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.3
ent_coef:
  value: 0.01
gae_lambda:
  value: 1
gamma:
  value: 0.864633313722988
learning_rate:
  value: 0.0003
log_std_init:
  value: 2
n_steps:
  value: 1024
target_kl:
  value: 0.026584693106269177
