wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.1
ent_coef:
  value: 0
gae_lambda:
  value: 0.9
gamma:
  value: 0.8068683530301097
learning_rate:
  value: 0.0003
log_std_init:
  value: 1
n_steps:
  value: 1024
target_kl:
  value: 0.00821395165650739
