wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.3
ent_coef:
  value: 0.001
gae_lambda:
  value: 1
gamma:
  value: 0.8014924526619729
learning_rate:
  value: 0.0003
log_std_init:
  value: 0
n_steps:
  value: 1024
target_kl:
  value: 0.022775446474251816
