wandb_version: 1

batch_size:
  value: 512
clip_range:
  value: 0.3
ent_coef:
  value: 0.001
gae_lambda:
  value: 0.9
gamma:
  value: 0.85556010945317
learning_rate:
  value: 0.0003
log_std_init:
  value: 1
n_steps:
  value: 256
target_kl:
  value: 0.007555206510131754
