wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.3
ent_coef:
  value: 0
gae_lambda:
  value: 1
gamma:
  value: 0.8458736368994498
learning_rate:
  value: 3.0e-05
log_std_init:
  value: 0
n_steps:
  value: 1024
target_kl:
  value: 0.012066394210691184
