wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.1
ent_coef:
  value: 0.01
gae_lambda:
  value: 1
gamma:
  value: 0.9291059695876924
learning_rate:
  value: 0.0003
log_std_init:
  value: 2
n_steps:
  value: 512
target_kl:
  value: 0.019296706884820485
