wandb_version: 1

batch_size:
  value: 512
clip_range:
  value: 0.3
ent_coef:
  value: 0.01
gae_lambda:
  value: 1
gamma:
  value: 0.9217280897050336
learning_rate:
  value: 0.0003
log_std_init:
  value: 0
n_steps:
  value: 256
target_kl:
  value: 0.020325109463369986
