wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.2
ent_coef:
  value: 0.0001
gae_lambda:
  value: 0.9
gamma:
  value: 0.8140820213070601
learning_rate:
  value: 3.0e-06
log_std_init:
  value: -2
n_steps:
  value: 256
target_kl:
  value: 0.012617038098938126
