wandb_version: 1

batch_size:
  value: 512
clip_range:
  value: 0.3
ent_coef:
  value: 0.001
gae_lambda:
  value: 0.9
gamma:
  value: 0.8383857975714469
learning_rate:
  value: 3.0e-06
log_std_init:
  value: 2
n_steps:
  value: 256
target_kl:
  value: 0.01692393435058707
