wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.3
ent_coef:
  value: 0.01
gae_lambda:
  value: 1
gamma:
  value: 0.9835745394982977
learning_rate:
  value: 3.0e-05
log_std_init:
  value: 1
n_steps:
  value: 512
target_kl:
  value: 0.02809920239634589
