wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.3
ent_coef:
  value: 0.001
gae_lambda:
  value: 0.9
gamma:
  value: 0.9797109918848842
learning_rate:
  value: 3.0e-05
log_std_init:
  value: 0
n_steps:
  value: 256
target_kl:
  value: 0.020027747866004333
