wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.1
ent_coef:
  value: 0.001
gae_lambda:
  value: 1
gamma:
  value: 0.910048824496058
learning_rate:
  value: 3.0e-06
log_std_init:
  value: 1
n_steps:
  value: 512
target_kl:
  value: 0.013667723662152388
