wandb_version: 1

batch_size:
  value: 512
clip_range:
  value: 0.3
ent_coef:
  value: 0.01
gae_lambda:
  value: 1
gamma:
  value: 0.9853282394671632
learning_rate:
  value: 3.0e-05
log_std_init:
  value: -2
n_steps:
  value: 256
target_kl:
  value: 0.00630826572079217
