wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.1
ent_coef:
  value: 0
gae_lambda:
  value: 0.9
gamma:
  value: 0.9078674958516478
learning_rate:
  value: 3.0e-05
log_std_init:
  value: -2
n_steps:
  value: 512
target_kl:
  value: 0.028200779587283887
