wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.1
ent_coef:
  value: 0.001
gae_lambda:
  value: 1
gamma:
  value: 0.9156118727617902
learning_rate:
  value: 0.0003
log_std_init:
  value: -2
n_steps:
  value: 1024
target_kl:
  value: 0.012901080413865607
