wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.1
ent_coef:
  value: 0
gae_lambda:
  value: 1
gamma:
  value: 0.8870564126123529
learning_rate:
  value: 0.0003
log_std_init:
  value: 2
n_steps:
  value: 256
target_kl:
  value: 0.012507063735375051
