wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.2
ent_coef:
  value: 0.001
gae_lambda:
  value: 1
gamma:
  value: 0.8096238650342699
learning_rate:
  value: 3.0e-06
log_std_init:
  value: -2
n_steps:
  value: 1024
target_kl:
  value: 0.019180211391168357
