wandb_version: 1

batch_size:
  value: 512
clip_range:
  value: 0.2
ent_coef:
  value: 0
gae_lambda:
  value: 0.9
gamma:
  value: 0.9419317068812876
learning_rate:
  value: 0.0003
log_std_init:
  value: 1
n_steps:
  value: 256
target_kl:
  value: 0.027998881452482895
