wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.2
ent_coef:
  value: 0.01
gae_lambda:
  value: 1
gamma:
  value: 0.9792297617520512
learning_rate:
  value: 3.0e-06
log_std_init:
  value: 0
n_steps:
  value: 256
target_kl:
  value: 0.015286190249706108
