wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.3
ent_coef:
  value: 0
gae_lambda:
  value: 1
gamma:
  value: 0.9233469905690186
learning_rate:
  value: 3.0e-06
log_std_init:
  value: -2
n_steps:
  value: 512
target_kl:
  value: 0.02476415786093626
