wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.3
ent_coef:
  value: 0.01
gae_lambda:
  value: 0.9
gamma:
  value: 0.909708677637552
learning_rate:
  value: 3.0e-06
log_std_init:
  value: 0
n_steps:
  value: 256
target_kl:
  value: 0.02260651606515587
