wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.3
ent_coef:
  value: 0
gae_lambda:
  value: 0.9
gamma:
  value: 0.9412051975438608
learning_rate:
  value: 0.0003
log_std_init:
  value: -2
n_steps:
  value: 1024
target_kl:
  value: 0.003354028338259343
