wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.3
ent_coef:
  value: 0.01
gae_lambda:
  value: 1
gamma:
  value: 0.9619676939739272
learning_rate:
  value: 0.0003
log_std_init:
  value: 0
n_steps:
  value: 512
target_kl:
  value: 0.006979523664971203
