wandb_version: 1

batch_size:
  value: 512
clip_range:
  value: 0.2
ent_coef:
  value: 0.001
gae_lambda:
  value: 0.9
gamma:
  value: 0.9579794148635484
learning_rate:
  value: 3.0e-06
log_std_init:
  value: 0
n_steps:
  value: 512
target_kl:
  value: 0.003827014741199956
