wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.3
ent_coef:
  value: 0.001
gae_lambda:
  value: 1
gamma:
  value: 0.9187447450358224
learning_rate:
  value: 3.0e-06
log_std_init:
  value: -2
n_steps:
  value: 256
target_kl:
  value: 0.01612058919490191
