wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.1
ent_coef:
  value: 0.0001
gae_lambda:
  value: 1
gamma:
  value: 0.8387293050818774
learning_rate:
  value: 0.0003
log_std_init:
  value: 0
n_steps:
  value: 256
target_kl:
  value: 0.021917743903440624
