wandb_version: 1

batch_size:
  value: 512
clip_range:
  value: 0.2
ent_coef:
  value: 0
gae_lambda:
  value: 1
gamma:
  value: 0.8587119013810676
learning_rate:
  value: 3.0e-05
log_std_init:
  value: 0
n_steps:
  value: 512
target_kl:
  value: 0.014537092045365551
