wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.1
ent_coef:
  value: 0.01
gae_lambda:
  value: 0.9
gamma:
  value: 0.9116200102868592
learning_rate:
  value: 3.0e-06
log_std_init:
  value: 1
n_steps:
  value: 1024
target_kl:
  value: 0.018283127452407944
