wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.3
ent_coef:
  value: 0.0001
gae_lambda:
  value: 0.9
gamma:
  value: 0.8482705756137637
learning_rate:
  value: 3.0e-05
log_std_init:
  value: 2
n_steps:
  value: 512
target_kl:
  value: 0.026911935017700873
