wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.2
ent_coef:
  value: 0.01
gae_lambda:
  value: 0.9
gamma:
  value: 0.8242438966334463
learning_rate:
  value: 3.0e-06
log_std_init:
  value: -1
n_steps:
  value: 512
target_kl:
  value: 0.01416213531955444
