wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.3
ent_coef:
  value: 0.001
gae_lambda:
  value: 1
gamma:
  value: 0.8756873753480428
learning_rate:
  value: 3.0e-05
log_std_init:
  value: 0
n_steps:
  value: 512
target_kl:
  value: 0.02375756403450031
