wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.2
ent_coef:
  value: 0.001
gae_lambda:
  value: 1
gamma:
  value: 0.832025712609925
learning_rate:
  value: 0.0003
log_std_init:
  value: 0
n_steps:
  value: 256
target_kl:
  value: 0.005466514696672234
