wandb_version: 1

batch_size:
  value: 512
clip_range:
  value: 0.3
ent_coef:
  value: 0.0001
gae_lambda:
  value: 1
gamma:
  value: 0.907935744947068
learning_rate:
  value: 3.0e-06
log_std_init:
  value: 0
n_steps:
  value: 256
target_kl:
  value: 0.025249161580593572
