wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.3
ent_coef:
  value: 0.01
gae_lambda:
  value: 0.9
gamma:
  value: 0.9289637780833075
learning_rate:
  value: 0.0003
log_std_init:
  value: -1
n_steps:
  value: 1024
target_kl:
  value: 0.017633345165137797
