wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.1
ent_coef:
  value: 0.0001
gae_lambda:
  value: 1
gamma:
  value: 0.8958175274928073
learning_rate:
  value: 0.0003
log_std_init:
  value: 1
n_steps:
  value: 1024
target_kl:
  value: 0.005806515158485617
