wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.1
ent_coef:
  value: 0.0001
gae_lambda:
  value: 0.9
gamma:
  value: 0.976861813372648
learning_rate:
  value: 3.0e-06
log_std_init:
  value: 0
n_steps:
  value: 512
target_kl:
  value: 0.023378524780154872
