wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.3
ent_coef:
  value: 0.01
gae_lambda:
  value: 0.9
gamma:
  value: 0.9574549769708436
learning_rate:
  value: 3.0e-06
log_std_init:
  value: 2
n_steps:
  value: 1024
target_kl:
  value: 0.0070497403104351234
total_timesteps:
  value: 20000
