_wandb:
    value:
        cli_version: 0.23.0
        e:
            e8wj464edk2ufo7sz0l286i6grit1i9p:
                args:
                    - --batch_size=64
                    - --clip_range=0.3
                    - --ent_coef=0
                    - --gamma=0.8829373804022405
                    - --learning_rate=0.0001
                    - --log_std_init=-2
                    - --n_steps=1024
                    - --total_timesteps=40000
                codePath: env\train.py
                codePathLocal: train.py
                cpu_count: 12
                cpu_count_logical: 16
                disk:
                    /:
                        total: "510745636864"
                        used: "358217891840"
                email: michellexu37@gmail.com
                executable: C:\Users\michellexu\anaconda3\envs\rlhr\python.exe
                git:
                    commit: eabf7c56eee683a7760b79f18da4b882a728b266
                    remote: https://github.com/michellexu222/rl-hemorrhage-resuscitation.git
                host: DESKTOP-JP5LEEC
                memory:
                    total: "16908300288"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\michellexu\Pulse\engine\src\python\pulse\rl-hemorrhage-resuscitation\env\train.py
                python: CPython 3.12.11
                root: C:\Users\michellexu\Pulse\engine\src\python\pulse\rl-hemorrhage-resuscitation\env
                startedAt: "2025-11-28T03:18:17.466392Z"
                writerId: e8wj464edk2ufo7sz0l286i6grit1i9p
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 14
                - 16
                - 22
                - 35
            "4": 3.12.11
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 64
clip_range:
    value: 0.3
ent_coef:
    value: 0
gamma:
    value: 0.8829373804022405
learning_rate:
    value: 0.0001
log_std_init:
    value: -2
method:
    value: bayes
metric:
    value:
        goal: maximize
        name: rollout/ep_rew_mean
n_steps:
    value: 1024
name:
    value: rppo_rlhr
parameters:
    value:
        batch_size:
            values:
                - 64
                - 128
                - 256
        clip_range:
            values:
                - 0.1
                - 0.2
                - 0.3
        ent_coef:
            values:
                - 0
                - 0.001
                - 0.01
        gamma:
            max: 0.9997
            min: 0.8
        learning_rate:
            values:
                - 3e-05
                - 0.0003
                - 0.0001
        log_std_init:
            values:
                - -2
                - -1
                - 0
                - 1
                - 2
        n_steps:
            values:
                - 512
                - 1024
        total_timesteps:
            values:
                - 20000
                - 40000
program:
    value: train.py
project:
    value: rlhr
total_timesteps:
    value: 40000
