wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.3
ent_coef:
  value: 0.001
gamma:
  value: 0.8619056494413345
learning_rate:
  value: 0.0001
log_std_init:
  value: 0
n_steps:
  value: 1024
total_timesteps:
  value: 40000
