wandb_version: 1

batch_size:
  value: 256
clip_range:
  value: 0.3
ent_coef:
  value: 0.01
gamma:
  value: 0.9530087794259042
learning_rate:
  value: 0.0001
log_std_init:
  value: -2
n_steps:
  value: 512
total_timesteps:
  value: 40000
