program: train.py
name: rppo_rlhr
project: rlhr
method: bayes
metric:
  name: rollout/ep_rew_mean
  goal: maximize

parameters:
  total_timesteps:
    values: [20000, 40000]
  learning_rate:
    values: [0.00003, 0.0003, 0.0001]
  gamma:
    min: 0.8
    max: 0.9997
  n_steps:
    values: [512, 1024]
  clip_range:
    values: [0.1, 0.2, 0.3]
  batch_size:
    values: [64, 128, 256]
  ent_coef:
    values: [0.0, 0.001, 0.01]
  log_std_init:
    values: [-2, -1, 0, 1, 2]

